# -*- coding: utf-8 -*-
"""TA final project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vgGq9D6MQrC0lNtUEQgfXY296s7iB0sh
"""

# install req libraries
!pip install -q spacy beautifulsoup4
!python -m spacy download en_core_web_sm


# Imports & load model

import spacy
from bs4 import BeautifulSoup
import networkx as nx
import matplotlib.pyplot as plt
from pathlib import Path
from collections import Counter, defaultdict

nlp = spacy.load("en_core_web_sm")


# Load local uploaded HTML

html_path = Path("/content/UEFA Euro 2024 - Wikipedia.html")  # <- your uploaded file
if not html_path.exists():
    raise FileNotFoundError(f"{html_path} not found. Put your HTML file here or change path.")

html_content = html_path.read_text(encoding="utf-8")
soup = BeautifulSoup(html_content, "lxml")
paras = [p.get_text(separator=" ", strip=True) for p in soup.find_all("p")]
text = "\n\n".join([p for p in paras if len(p) > 40])   # filter tiny paras


def token_to_entity_map(doc):
    """Return dict mapping token.i -> entity Span (or None)."""
    token_ent = {tok.i: None for tok in doc}
    for ent in doc.ents:
        for i in range(ent.start, ent.end):
            token_ent[i] = ent
    return token_ent


# Entity extraction

doc = nlp(text)
print("Total characters:", len(text))
print("Detected entity types counts:")
ent_type_counts = Counter([ent.label_ for ent in doc.ents])
print(ent_type_counts.most_common())


# Relation extraction

def extract_relations_from_doc(doc, max_sentences=None):
    relations = []
    sents = list(doc.sents)
    if max_sentences:
        sents = sents[:max_sentences]
    for sent in sents:
        token_ent = token_to_entity_map(sent)  e
        for token in sent:
            if token.pos_ == "VERB":
                # find subject tokens in subtree
                subj_tokens = [w for w in token.subtree if w.dep_ in ("nsubj", "nsubjpass", "csubj")]
                obj_tokens  = [w for w in token.subtree if w.dep_ in ("dobj", "obj", "pobj", "attr", "dative")]

                # Map tokens to entities)
                subj_ents = []
                obj_ents = []
                for st in subj_tokens:
                    ent = token_ent.get(st.i)
                    if ent is not None:
                        subj_ents.append(ent.text.strip())
                for ot in obj_tokens:
                    ent = token_ent.get(ot.i)
                    if ent is not None:
                        obj_ents.append(ent.text.strip())

                # fallback: if no subj/entity found, try nearest entity left/right
                if not subj_ents and sent.ents:
                    left_ents = [ent for ent in sent.ents if ent.end <= token.i]
                    if left_ents:
                        subj_ents.append(left_ents[-1].text.strip())
                if not obj_ents and sent.ents:
                    right_ents = [ent for ent in sent.ents if ent.start >= token.i]
                    if right_ents:
                        obj_ents.append(right_ents[0].text.strip())

                for s in subj_ents:
                    for o in obj_ents:
                        if s and o and s.lower() != o.lower():
                            relations.append((s, token.lemma_.lower(), o))
    # deduplicate
    uniq = []
    seen = set()
    for r in relations:
        if r not in seen:
            uniq.append(r); seen.add(r)
    return uniq

# For speed while developing, you can limit sentences, e.g., max_sentences=1000
triples = extract_relations_from_doc(doc, max_sentences=None)
print("Extracted triples count:", len(triples))
print("Sample triples:", triples[:15])

# Building weighted NetworkX graph

G = nx.DiGraph()
edge_counter = Counter()
node_counter = Counter()

for s, rel, o in triples:
    edge_counter[(s, o, rel)] += 1
    node_counter[s] += 1
    node_counter[o] += 1

# Aggregate edges by (s,o) and collect multiple relation labels
for (s,o,rel), w in edge_counter.items():
    if not G.has_node(s): G.add_node(s)
    if not G.has_node(o): G.add_node(o)
    if G.has_edge(s,o):
        G[s][o]["weight"] += w
        G[s][o]["relations"].add(rel)
    else:
        G.add_edge(s,o, weight=w, relations=set([rel]))

print("Graph nodes:", G.number_of_nodes(), "edges:", G.number_of_edges())

# Optional: prune graph to reduce noise for plotting
# - keep only nodes with degree >= threshold or only top N edges by weight

# Keep only edges with weight >= 2 (tune this)
min_edge_weight = 2
H = nx.DiGraph()
for u,v,data in G.edges(data=True):
    if data.get("weight",1) >= min_edge_weight:
        H.add_node(u); H.add_node(v)
        H.add_edge(u,v, **data)

print("Pruned graph nodes:", H.number_of_nodes(), "edges:", H.number_of_edges())

# If pruning removes everything, fallback to original G
if H.number_of_nodes() == 0:
    H = G

# -------------------------
# Plot (pruned)
# -------------------------
plt.figure(figsize=(14,10))
pos = nx.spring_layout(H, k=0.6, seed=42)
node_sizes = [300 + 150*H.degree(n) for n in H.nodes()]
nx.draw_networkx_nodes(H, pos, node_size=node_sizes, node_color="skyblue", alpha=0.9)
nx.draw_networkx_labels(H, pos, font_size=9)
nx.draw_networkx_edges(H, pos, alpha=0.6, arrowsize=12)
edge_labels = { (u,v): ",".join(sorted(list(data["relations"]))) for u,v,data in H.edges(data=True) }
nx.draw_networkx_edge_labels(H, pos, edge_labels=edge_labels, font_size=8)
plt.title("Knowledge Graph (pruned, weight>={})".format(min_edge_weight))
plt.axis("off")
plt.show()

# -------------------------
# Export CSVs for Neo4j if needed
# -------------------------
import pandas as pd
nodes = [{"id": n, "degree": H.degree(n)} for n in H.nodes()]
edges = [{"source": u, "target": v, "weight": data.get("weight",1), "relations": "|".join(sorted(list(data.get("relations",[]))))}
         for u,v,data in H.edges(data=True)]
pd.DataFrame(nodes).to_csv("/content/kg_nodes_pruned.csv", index=False)
pd.DataFrame(edges).to_csv("/content/kg_edges_pruned.csv", index=False)
print("Wrote /content/kg_nodes_pruned.csv and /content/kg_edges_pruned.csv")